### ISSUE TITLE
Error: No free hard points on Head

### ISSUE THREAD

**Issue by nickdiesel** [EmilyBjoerk/lsml#433]
LSML version: 1.6.9003

Steps to reproduce:
1. Launch LSML
2. Receive the error below, press "OK" twelve times.
3. Menu bar only loads, no mech builds or garages load.

Notes: This occurs even after removing old garage, lsml_settings.xml and lsml_datacache.xml files.

Actual result: Receive the following error 12 times, then program loads but nothing is available.

No free hard points on Head
	at org.lisoft.lsml.model.loadout.EquipResult.<clinit>(EquipResult.java:83)
	at org.lisoft.lsml.model.loadout.LoadoutBase.canEquipGlobal(LoadoutBase.java:521)
	at org.lisoft.lsml.model.loadout.LoadoutBase.canEquip(LoadoutBase.java:446)
	at org.lisoft.lsml.command.CmdAddItem.apply(CmdAddItem.java:83)
	at org.lisoft.lsml.util.CommandStack$CompositeCommand.apply(CommandStack.java:117)
	at org.lisoft.lsml.util.CommandStack.pushAndApply(CommandStack.java:220)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceStock(DefaultLoadoutFactory.java:83)
	at org.lisoft.lsml.view.ChassiSelectionPane$PartColumn$1.getTableCellRendererComponent(ChassiSelectionPane.java:252)
	at javax.swing.JTable.prepareRenderer(Unknown Source)
	at org.lisoft.lsml.view.ChassiSelectionPane.resizeColumnWidth(ChassiSelectionPane.java:404)
	at org.lisoft.lsml.view.ChassiSelectionPane.<init>(ChassiSelectionPane.java:363)
	at org.lisoft.lsml.view.LSML.<init>(LSML.java:134)
	at org.lisoft.lsml.view.ProgramInit$1.run(ProgramInit.java:133)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Expected result: Program launches and is available for normal operation.

**Comment by EmilyBjoerk** [comment]
I cannot reproduce this error. Can you send me your `lsml_settings.xml` and the path of your game install?

**Comment by EmilyBjoerk** [comment]
Never mind, I hadn't patched... looks like PGI broke something again. I'll put out a patch soon.

**Comment by EmilyBjoerk** [comment]
The bug is due to a previously unparsed actuator state in stock loadouts preventing a proper loadout from being generated.

This is three bugs:
1) The error should not leave the UI in an unusable state. 
2) The reported error should be clearer.
3) The actuator state should be parsed and made a part of stock loadouts.
