### ISSUE TITLE
Crash with 2016-10-18 update

### ISSUE THREAD

**Issue by Maberi** [EmilyBjoerk/lsml#627]
Not compatible with 2016-10-18 update. Several errors.

**Comment by EmilyBjoerk** [comment]
I'm currently traveling, I will look into this when I'm back home next week.

**Comment by Maberi** [comment]
You shoud avoid travel on mayor MWO patches :D

Just kidding, but, may be, you could save the info you extract from the game in some own format to recover it from there in case of change in MWO.

**Comment by EmilyBjoerk** [comment]
That's not very funny unfortunately, I work very hard on this you know... :crying_cat_face: 

I already store the data that is extracted, however it appears PGI changed something big or unexpected to the parser took a nose dive attempting to make sense of it all. Although I've taken precautions for that to not happen, some times it does when you try to hit a moving target that is MWO's data files.

**Comment by Maberi** [comment]
I understand the complexities. What about leaving the parsed data in a server you control? Or just here, in github. You would save locating MWO install path and prevent crashes on patches.

BTW, I appreciate your work and I've just suscribed to patreon. Not a big ammount, but a sign of aknowledging to your work.

**Comment by EmilyBjoerk** [comment]
The data is left on your computer, in `%appdata%`. The parser when it fails will just read the last successful parse. However something causes it to crash horribly...

**Comment by EmilyBjoerk** [comment]
I do not get a crash? I get some errors about the data files but LSML is still working fine.

Do you get an actual crash or does LSML still start up?

**Comment by Maberi** [comment]
1st error: error window with message: There exists no original ominpod for SMN-M(L) at Head
2nd: same with HBR-F(L)
3rd: SMN-F(L)

Opening existing garage mechs is working.

Creating new mech: error "Li Song Mechlab has encountered an unexpected error."

Stack:
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8413)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.Trampoline.invoke(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771)
	... 48 more
Caused by: java.lang.IllegalArgumentException: There exists no original omnipod for HBR-F(L) at Head
	at org.lisoft.lsml.model.datacache.OmniPodDB.lookupOriginal(OmniPodDB.java:149)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceEmpty(DefaultLoadoutFactory.java:168)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceDefault(DefaultLoadoutFactory.java:100)
	at org.lisoft.lsml.model.chassi.ChassisFilter.<init>(ChassisFilter.java:232)
	at org.lisoft.lsml.view_fx.NewMechPane.<init>(NewMechPane.java:103)
	at org.lisoft.lsml.view_fx.MainWindow.openNewMechOverlay(MainWindow.java:149)
	... 58 more

**Comment by Maberi** [comment]
It doesn't seem a blocking issue since you may create new mechs through chassis list

**Comment by EmilyBjoerk** [comment]
Please don't joke about that, it's disheartening and makes me sad. 😔

It already does that. It's just that pgi presumably changed the data files
in some unexpected way that made the parser not only fail, but crash ( I've
taken steps to prevent that but obviously I've missed some thing).

I'll be back in a few days, just sit tight.
