### ISSUE TITLE
Last patch broke the mechlab

### ISSUE THREAD

**Issue by Smokey2** [EmilyBjoerk/lsml#663]
Get this on startup.

java.lang.ExceptionInInitializerError
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$start$12(LiSongMechLab.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:126)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)
	at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:63)
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1094)
	at org.lisoft.lsml.model.garage.GarageSerialiser.load(GarageSerialiser.java:84)
	at org.lisoft.lsml.view_fx.GlobalGarage.autoLoadLastGarage(GlobalGarage.java:289)
	at org.lisoft.lsml.view_fx.GlobalGarage.<clinit>(GlobalGarage.java:73)
	... 20 more
Caused by: java.io.EOFException: input contained no data
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 31 more

**LSML version:** x.y.z
**Screen resolution:** 1920x1200
**Java version:** 8uX

**Steps to reproduce issue:**
1. Open LSML
2. Click on ... 
3. Then on ...
4. Finally do this...

**Actual result:**
Nothing/something happened

**Expected result:**
Something else should have happened

**Comment by EmilyBjoerk** [comment]
Duplicate of #661.
