### ISSUE TITLE
Update to 2.0.6 Exception stacktrace

### ISSUE THREAD

**Issue by VoodooLouKerensky** [EmilyBjoerk/lsml#670]
**LSML version:** 2.05
**Screen resolution:** 1920x1200
**Java version:** 8uX

**Steps to reproduce issue:**
1. Open LSML
2. Click on Update to 2.0.6
3. Then on download
4. Finally do this frown at the error message and copy and paste what the exception stacktrace is

**Actual result:**
java.lang.IllegalArgumentException: There exists no original omnipod for HBR-F at Head
	at org.lisoft.lsml.model.datacache.OmniPodDB.lookupOriginal(OmniPodDB.java:149)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceEmpty(DefaultLoadoutFactory.java:168)
	at org.lisoft.lsml.view_fx.ChassisPage.setupTableData(ChassisPage.java:282)
	at org.lisoft.lsml.view_fx.ChassisPage.setupChassisTable(ChassisPage.java:172)
	at org.lisoft.lsml.view_fx.ChassisPage.<init>(ChassisPage.java:152)
	at org.lisoft.lsml.view_fx.MainWindow.<init>(MainWindow.java:77)
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$start$12(LiSongMechLab.java:496)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:218)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$null$4(LiSongMechLab.java:272)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

**Expected result:**
Update and continue on

**Comment by EmilyBjoerk** [comment]
Did you actually download and install the update from the web? It's not
automatic.

**Comment by VoodooLouKerensky** [comment]
Salutations,
Will do so and see if that solves it. Mightve been a permissions conflict with the Launcher Download button request to browser to open download page and my browser even as Admin. With Win10 and the sneaky shit it has I wouldn’t be surprised if theres something Ive got blocked because of BS on windows I don’t use so got rid of that might be biting me in the ass now too. Since my MWO profile lists my current mech as NA and has been doing that for quite some time.
Will inform of pass/fail after DL,
Thanks for prompt response.

Bill ’VoodooLou Kerensky’ Warren Jr

**Comment by EmilyBjoerk** [comment]
As there has been no further communication on the issue, I will assume that it has been resolved by downloading and installing the update. I will close the issue, if you still have problems, please feel free to re-open the issue.
