### ISSUE TITLE
LSML won't open, hangs on "parsing game data"

### ISSUE THREAD

**Issue by insanity09** [EmilyBjoerk/lsml#672]
**LSML version:** 2.0.6
**Screen resolution:** 1680x1050
**Java version: 8 update 121

**Steps to reproduce issue:**
1. Open LSML
2. See error message, click on okay (after copying details, see below)
3. Watch "parsing game data" message until I need to reboot my computer.
4. Finally do this...

**Actual result:**
Nothing happened

**Expected result:**
LSML should have opened.

Error text (minus the extra 59 entries?)
```
java.lang.ExceptionInInitializerError
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$start$12(LiSongMechLab.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.io.StreamException
cause-message       : 
class               : org.lisoft.lsml.model.upgrades.Upgrades
required-type       : org.lisoft.lsml.model.upgrades.Upgrades
converter-type      : org.lisoft.lsml.model.export.garage.UpgradesConverter
line number         : 1769
class[1]            : org.lisoft.lsml.model.loadout.LoadoutStandard
converter-type[1]   : org.lisoft.lsml.model.export.garage.LoadoutConverter
class[2]            : java.util.ArrayList
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[3]            : org.lisoft.lsml.model.garage.GarageDirectory
converter-type[3]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[4]            : org.lisoft.lsml.model.garage.Garage
converter-type[4]   : org.lisoft.lsml.model.export.garage.GarageConverter
version             : 2.0.6
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at org.lisoft.lsml.model.export.garage.LoadoutConverter.parseV2(LoadoutConverter.java:196)
	at org.lisoft.lsml.model.export.garage.LoadoutConverter.unmarshal(LoadoutConverter.java:129)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:73)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:91)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:85)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at org.lisoft.lsml.model.export.garage.GarageConverter.unmarshal(GarageConverter.java:118)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1094)
	at org.lisoft.lsml.model.garage.GarageSerialiser.load(GarageSerialiser.java:84)
	at org.lisoft.lsml.view_fx.GlobalGarage.autoLoadLastGarage(GlobalGarage.java:289)
	at org.lisoft.lsml.view_fx.GlobalGarage.<clinit>(GlobalGarage.java:73)
	... 20 more
Caused by: com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:126)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.hasMoreChildren(AbstractPullReader.java:87)
	at org.lisoft.lsml.model.export.garage.UpgradesConverter.unmarshal(UpgradesConverter.java:121)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 54 more
Caused by: java.io.EOFException: no more data available - expected end tags </upgrades></loadout></values></loadouts></garage> to close start tag <upgrades> from line 1764 and start tag <loadout> from line 1756 and start tag <values> from line 9 and start tag <loadouts> from line 2 and start tag <garage> from line 1, parser stopped on END_TAG seen ...</heatsinks>\n... @1769:1
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1384)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 59 more

```

**Comment by EmilyBjoerk** [comment]
It looks like LSML failed to read it's own data cache. Maybe it got corrupted some how... try to remove `%APPDATA%/LiSoft/LSML/datacache.xml` and see if it works.

**Comment by insanity09** [comment]
Hello, 
The location was a tad different, I found it in %appdata%/roaming/lisoft/lsml .The listed file was a bit different, instead of datacache.xml, the only file listed was settings.xml.However, I deleted that and the lab did finally open.  Thank you!There are now two .xml files in that location, settings and data_cache.
While I'm still a bit puzzled over this, working is working, so I'm happy.
Thanks,Eric Heidel
PS:  Could some of these differences be because I'm running the 64bit version?

**Comment by EmilyBjoerk** [comment]
It has nothing to do with 64bits. The file got corrupted either because: LSML shut down improperly in the middle of writing the file (bluescreen or the sorts, this is very rare). Or your harddrive is on the verge of failing or just had a barf when it wrote the file. It shouldn't happen but it can with dodgy hardware.
