### ISSUE TITLE
NPE when hovering over rocket launcher in equipment list.

### ISSUE THREAD

**Issue by EmilyBjoerk** [EmilyBjoerk/lsml#694]
java.lang.NullPointerException
	at org.lisoft.lsml.view_fx.style.ItemToolTipFormatter.formatWeapon(ItemToolTipFormatter.java:203)
	at org.lisoft.lsml.view_fx.style.ItemToolTipFormatter.format(ItemToolTipFormatter.java:140)
	at org.lisoft.lsml.view_fx.controls.EquipmentTableCell.lambda$1(EquipmentTableCell.java:64)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.lisoft.lsml.view_fx.controls.EquipmentTableCell.lambda$0(EquipmentTableCell.java:57)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

**Comment by EmilyBjoerk** [comment]
Was fixed by commit 9de0557d35c14aa0c7a23d5992960b5f6f0f2997
