### ISSUE TITLE
NPE when attempting to swap clan omnimech's side torso omnipod

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#702]
Clicking on the side torso omnipod drop-down list immediately causes NPE:

```
java.lang.NullPointerException
	at org.lisoft.lsml.view_fx.util.EquipmentCategory.classify(EquipmentCategory.java:60)
	at org.lisoft.lsml.view_fx.util.EquipmentCategory.classify(EquipmentCategory.java:98)
	at org.lisoft.lsml.view_fx.style.HardPointFormatter.format(HardPointFormatter.java:59)
	at org.lisoft.lsml.view_fx.controls.OmniPodListCell.updateItem(OmniPodListCell.java:64)
	at org.lisoft.lsml.view_fx.controls.OmniPodListCell.updateItem(OmniPodListCell.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
```

I believe this applies to every omnimech. Try TBR.

**Comment by EmilyBjoerk** [comment]
Is this in 2.0.7?

**Comment by VioletGiraffe** [comment]
Yes, it was in 2.0.7. I've tried a couple other omnimechs and none worked. Hopefully you've fixed it all, thanks.

**Comment by EmilyBjoerk** [comment]
For me, gargoyle worked. TBR didn't. The issue was if the omnipod had fixed jump-jets or not. If you could list other chassis that didn't work I can confirm them.

**Comment by VioletGiraffe** [comment]
I can only recall Huntsman, which does indeed have the JJs. Makes sense.

**Comment by VioletGiraffe** [comment]
The only other mech affected by this I could find is DWF.

**Comment by EmilyBjoerk** [comment]
Confirmed, works for DWF and KFX after fix.
