### ISSUE TITLE
Cant swap kit fox side torso pods

### ISSUE THREAD

**Issue by Question2** [EmilyBjoerk/lsml#706]
When i try to swap kit fox side torso pods, i just get this error : 

java.lang.NullPointerException
	at org.lisoft.lsml.view_fx.util.EquipmentCategory.classify(EquipmentCategory.java:60)
	at org.lisoft.lsml.view_fx.util.EquipmentCategory.classify(EquipmentCategory.java:98)
	at org.lisoft.lsml.view_fx.style.HardPointFormatter.format(HardPointFormatter.java:59)
	at org.lisoft.lsml.view_fx.controls.OmniPodListCell.updateItem(OmniPodListCell.java:64)
	at org.lisoft.lsml.view_fx.controls.OmniPodListCell.updateItem(OmniPodListCell.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)

**Comment by EmilyBjoerk** [comment]
I am no longer able to reproduce this. I assume something else I did fixed it already. Closing the issue, please feel free to re-open the issue if it persists after 2.0.8 is released.
